export const banks = [
  { bankName: "AB MICROFINANCE BANK", CBNBankCode: "433", NIBBSCode: "090270" },
  { bankName: "ABBEY MORTGAGE BANK", CBNBankCode: "924", NIBBSCode: "070010" },
  {
    bankName: "ABOVE ONLY MICROFINANCE BANK",
    CBNBankCode: "398",
    NIBBSCode: "090260",
  },
  {
    bankName: "ABU MICROFINANCE BANK",
    CBNBankCode: "393",
    NIBBSCode: "090197",
  },
  { bankName: "ACCESS BANK", CBNBankCode: "044", NIBBSCode: "000014" },
  { bankName: "ACCESS(DIAMOND) BANK", CBNBankCode: "063", NIBBSCode: "000005" },
  {
    bankName: "ACCION MICROFINANCE BANK",
    CBNBankCode: "936",
    NIBBSCode: "090134",
  },
  {
    bankName: "ADDOSSER MICROFINANCE BANK",
    CBNBankCode: "953",
    NIBBSCode: "090160",
  },
  {
    bankName: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK",
    CBNBankCode: "969",
    NIBBSCode: "090268",
  },
  {
    bankName: "ALEKUN MICROFINANCE BANK",
    CBNBankCode: "397",
    NIBBSCode: "090259",
  },
  {
    bankName: "ALLWORKERS MICROFINANCE BANK",
    CBNBankCode: "933",
    NIBBSCode: "090131",
  },
  {
    bankName: "AMML MICROFINANCE BANK",
    CBNBankCode: "910",
    NIBBSCode: "090116",
  },
  {
    bankName: "APEKS MICROFINANCE BANK",
    CBNBankCode: "947",
    NIBBSCode: "090143",
  },
  {
    bankName: "ARISE MICROFINANCE BANK",
    CBNBankCode: "441",
    NIBBSCode: "090282",
  },
  {
    bankName: "ASTRAPOLARIS MICROFINANCE BANK",
    CBNBankCode: "979",
    NIBBSCode: "090172",
  },
  {
    bankName: "AUCHI MICROFINANCE BANK",
    CBNBankCode: "431",
    NIBBSCode: "090264",
  },
  {
    bankName: "BC KASH MICROFINANCE BANK",
    CBNBankCode: "930",
    NIBBSCode: "090127",
  },
  {
    bankName: "BOSAK MICROFINANCE BANK",
    CBNBankCode: "385",
    NIBBSCode: "090176",
  },
  {
    bankName: "BOWEN MICROFINANCE BANK",
    CBNBankCode: "367",
    NIBBSCode: "090148",
  },
  { bankName: "BRENT MORTGAGE BANK", CBNBankCode: "952", NIBBSCode: "070015" },
  { bankName: "CELLULANT", CBNBankCode: "317", NIBBSCode: "100005" },
  {
    bankName: "CEMCS MICROFINANCE BANK",
    CBNBankCode: "370",
    NIBBSCode: "090154",
  },
  {
    bankName: "CHIKUM MICROFINANCE BANK",
    CBNBankCode: "363",
    NIBBSCode: "090141",
  },
  {
    bankName: "CIT MICROFINANCE BANK",
    CBNBankCode: "364",
    NIBBSCode: "090144",
  },
  { bankName: "CITI BANK", CBNBankCode: "023", NIBBSCode: "000009" },
  {
    bankName: "CONSUMER MICROFINANCE BANK",
    CBNBankCode: "922",
    NIBBSCode: "090130",
  },
  {
    bankName: "CREDIT AFRIQUE MICROFINANCE BANK",
    CBNBankCode: "373",
    NIBBSCode: "090159",
  },
  {
    bankName: "DAYLIGHT MICROFINANCE BANK",
    CBNBankCode: "380",
    NIBBSCode: "090167",
  },
  { bankName: "EARTHOLEUM", CBNBankCode: "302", NIBBSCode: "100021" },
  {
    bankName: "E-BARCS MICROFINANCE BANK",
    CBNBankCode: "371",
    NIBBSCode: "090156",
  },
  { bankName: "ECOBANK", CBNBankCode: "050", NIBBSCode: "000010" },
  { bankName: "ECOMOBILE", CBNBankCode: "307", NIBBSCode: "100030" },
  {
    bankName: "EKONDO MICROFINANCE BANK",
    CBNBankCode: "903",
    NIBBSCode: "090097",
  },
  {
    bankName: "EMERALDS MICROFINANCE BANK",
    CBNBankCode: "973",
    NIBBSCode: "090273",
  },
  {
    bankName: "EMPIRE TRUST MICROFINANCE BANK",
    CBNBankCode: "972",
    NIBBSCode: "090114",
  },
  { bankName: "ENTERPRISE BANK", CBNBankCode: "084", NIBBSCode: "000019" },
  { bankName: "ETRANZACT", CBNBankCode: "306", NIBBSCode: "100006" },
  {
    bankName: "FAST MICROFINANCE BANK",
    CBNBankCode: "387",
    NIBBSCode: "090179",
  },
  {
    bankName: "FBNQUEST MERCHANT BANK",
    CBNBankCode: "923",
    NIBBSCode: "060002",
  },
  { bankName: "FCMB MOBILE", CBNBankCode: "954", NIBBSCode: "100031" },
  { bankName: "FET", CBNBankCode: "314", NIBBSCode: "100001" },
  {
    bankName: "FFS MICROFINANCE BANK",
    CBNBankCode: "369",
    NIBBSCode: "090153",
  },
  { bankName: "FIDELITY BANK", CBNBankCode: "070", NIBBSCode: "000007" },
  { bankName: "FIDELITY MOBILE X", CBNBankCode: "NA", NIBBSCode: "100019" },
  {
    bankName: "FIDFUND MICROFINANCE BANK",
    CBNBankCode: "929",
    NIBBSCode: "090126",
  },
  {
    bankName: "FINATRUST MICROFINANCE BANK",
    CBNBankCode: "906",
    NIBBSCode: "090111",
  },
  {
    bankName: "FIRST BANK OF NIGERIA",
    CBNBankCode: "011",
    NIBBSCode: "000016",
  },
  {
    bankName: "FIRST CITY MONUMENT BANK",
    CBNBankCode: "214",
    NIBBSCode: "000003",
  },
  {
    bankName: "FIRST GENERATION MORTGAGE BANK",
    CBNBankCode: "959",
    NIBBSCode: "070014",
  },
  {
    bankName: "FORTIS MICROFINANCE BANK",
    CBNBankCode: "501",
    NIBBSCode: "070002",
  },
  { bankName: "FSDH", CBNBankCode: "601", NIBBSCode: "400001" },
  {
    bankName: "FUTO MICROFINANCE BANK",
    CBNBankCode: "372",
    NIBBSCode: "090158",
  },
  {
    bankName: "GATEWAY MORTGAGE BANK",
    CBNBankCode: "921",
    NIBBSCode: "070009",
  },
  {
    bankName: "GOWANS MICROFINANCE BANK",
    CBNBankCode: "917",
    NIBBSCode: "090122",
  },
  {
    bankName: "GREENBANK MICROFINANCE BANK",
    CBNBankCode: "386",
    NIBBSCode: "090178",
  },
  {
    bankName: "GROOMING MICROFINANCE BANK",
    CBNBankCode: "391",
    NIBBSCode: "090195",
  },
  { bankName: "GTBANK PLC", CBNBankCode: "058", NIBBSCode: "000013" },
  {
    bankName: "HACKMAN MICROFINANCE BANK",
    CBNBankCode: "366",
    NIBBSCode: "090147",
  },
  {
    bankName: "HASAL MICROFINANCE BANK",
    CBNBankCode: "926",
    NIBBSCode: "090121",
  },
  { bankName: "HEDONMARK", CBNBankCode: "324", NIBBSCode: "100017" },
  {
    bankName: "IBILE MICROFINANCE BANK",
    CBNBankCode: "920",
    NIBBSCode: "090118",
  },
  {
    bankName: "IMO STATE MICROFINANCE BANK",
    CBNBankCode: "974",
    NIBBSCode: "090258",
  },
  {
    bankName: "INFINITY MICROFINANCE BANK",
    CBNBankCode: "958",
    NIBBSCode: "090157",
  },
  {
    bankName: "INNOVECTIVES KESH",
    CBNBankCode: "937",
    NIBBSCode: "100029",
  },
  {
    bankName: "IRL MICROFINANCE BANK",
    CBNBankCode: "949",
    NIBBSCode: "090149",
  },
  { bankName: "JAIZ BANK", CBNBankCode: "301", NIBBSCode: "000006" },
  { bankName: "KEYSTONE BANK", CBNBankCode: "082", NIBBSCode: "000002" },
  { bankName: "KONGAPAY", CBNBankCode: "912", NIBBSCode: "100025" },
  {
    bankName: "KUDA MICROFINANCE BANK",
    CBNBankCode: "981",
    NIBBSCode: "100011",
  },
  {
    bankName: "MAINSTREET MICROFINANCE BANK",
    CBNBankCode: "960",
    NIBBSCode: "090171",
  },
  {
    bankName: "MEGAPRAISE MICROFINANCE BANK",
    CBNBankCode: "802",
    NIBBSCode: "090280",
  },
  {
    bankName: "MICROCRED MICROFINANCE BANK",
    CBNBankCode: "941",
    NIBBSCode: "090136",
  },
  {
    bankName: "MONEY TRUST MICROFINANCE BANK",
    CBNBankCode: "951",
    NIBBSCode: "090129",
  },
  {
    bankName: "MUTUAL TRUST MICROFINANCE BANK",
    CBNBankCode: "966",
    NIBBSCode: "090151",
  },
  {
    bankName: "NDIORAH MICROFINANCE BANK",
    CBNBankCode: "931",
    NIBBSCode: "090128",
  },
  {
    bankName: "NEW DAWN MICROFINANCE BANK",
    CBNBankCode: "971",
    NIBBSCode: "090205",
  },
  {
    bankName: "NIGERIAN NAVY MICROFINANCE BANK",
    CBNBankCode: "567",
    NIBBSCode: "090263",
  },
  { bankName: "NIP VIRTUAL BANK", CBNBankCode: "999", NIBBSCode: "999999" },
  {
    bankName: "NPF MICROFINANCE BANK",
    CBNBankCode: "982",
    NIBBSCode: "070001",
  },
  {
    bankName: "OHAFIA MICROFINANCE BANK",
    CBNBankCode: "915",
    NIBBSCode: "090119",
  },
  {
    bankName: "OKPOGA MICROFINANCE BANK",
    CBNBankCode: "374",
    NIBBSCode: "090161",
  },
  {
    bankName: "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK",
    CBNBankCode: "355",
    NIBBSCode: "090272",
  },
  { bankName: "OMOLUABI SAVINGS", CBNBankCode: "901", NIBBSCode: "070007" },
  { bankName: "ONE FINANCE", CBNBankCode: "565", NIBBSCode: "100026" },
  { bankName: "PAGATECH", CBNBankCode: "327", NIBBSCode: "100002" },
  {
    bankName: "PARKWAY-READYCASH",
    CBNBankCode: "311",
    NIBBSCode: "100003",
  },
  {
    bankName: "PAYATTITUDE ONLINE",
    CBNBankCode: "329",
    NIBBSCode: "110001",
  },
  { bankName: "PAYCOM", CBNBankCode: "305", NIBBSCode: "100004" },
  {
    bankName: "PENNYWISE MICROFINANCE BANK",
    CBNBankCode: "392",
    NIBBSCode: "090196",
  },
  {
    bankName: "PERSONAL TRUST MICROFINANCE BANK",
    CBNBankCode: "939",
    NIBBSCode: "090135",
  },
  {
    bankName: "PLATINUM MORTGAGE BANK",
    CBNBankCode: "994",
    NIBBSCode: "070013",
  },
  { bankName: "POLARIS BANK", CBNBankCode: "076", NIBBSCode: "000008" },
  {
    bankName: "PRESTIGE MICROFINANCE BANK",
    CBNBankCode: "360",
    NIBBSCode: "090274",
  },
  { bankName: "PROVIDUS BANK", CBNBankCode: "101", NIBBSCode: "000023" },
  {
    bankName: "QUICKFUND MICROFINANCE BANK",
    CBNBankCode: "399",
    NIBBSCode: "090261",
  },
  {
    bankName: "RAND MERCHANT BANK",
    CBNBankCode: "902",
    NIBBSCode: "000024",
  },
  {
    bankName: "REFUGE MORTGAGE BANK",
    CBNBankCode: "925",
    NIBBSCode: "070011",
  },
  {
    bankName: "REGENT MICROFINANCE BANK",
    CBNBankCode: "919",
    NIBBSCode: "090125",
  },
  {
    bankName: "RENMONEY MICROFINANCE BANK",
    CBNBankCode: "394",
    NIBBSCode: "090198",
  },
  {
    bankName: "RICHWAY MICROFINANCE BANK",
    CBNBankCode: "934",
    NIBBSCode: "090132",
  },
  {
    bankName: "SAGAMU MICROFINANCE BANK",
    CBNBankCode: "945",
    NIBBSCode: "090140",
  },
  {
    bankName: "SEED CAPITAL MICROFINANCE BANK",
    CBNBankCode: "907",
    NIBBSCode: "090112",
  },
  {
    bankName: "STANBIC IBTC BANK",
    CBNBankCode: "221",
    NIBBSCode: "000012",
  },
  {
    bankName: "STELLAS MICROFINANCE BANK",
    CBNBankCode: "400",
    NIBBSCode: "090262",
  },
  { bankName: "STERLING BANK", CBNBankCode: "232", NIBBSCode: "000001" },
  { bankName: "STERLING MOBILE", CBNBankCode: "991", NIBBSCode: "100022" },
  { bankName: "SUNTRUST BANK", CBNBankCode: "100", NIBBSCode: "000022" },
  { bankName: "TAGPAY", CBNBankCode: "992", NIBBSCode: "100023" },
  { bankName: "TAJ BANK", CBNBankCode: "330", NIBBSCode: "000026" },
  {
    bankName: "TCF MICROFINANCE BANK",
    CBNBankCode: "909",
    NIBBSCode: "090115",
  },
  { bankName: "TEASYMOBILE", CBNBankCode: "319", NIBBSCode: "100010" },
  {
    bankName: "TRIDENT MICROFINANCE BANK",
    CBNBankCode: "948",
    NIBBSCode: "090146",
  },
  { bankName: "TRUSTBOND", CBNBankCode: "523", NIBBSCode: "090005" },
  {
    bankName: "TRUSTFUND MICROFINANCE BANK",
    CBNBankCode: "436",
    NIBBSCode: "090276",
  },
  { bankName: "UNION BANK", CBNBankCode: "032", NIBBSCode: "000018" },
  {
    bankName: "UNITED BANK FOR AFRICA",
    CBNBankCode: "033",
    NIBBSCode: "000004",
  },
  { bankName: "UNITY BANK", CBNBankCode: "215", NIBBSCode: "000011" },
  {
    bankName: "VFD MICROFINANCE BANK",
    CBNBankCode: "566",
    NIBBSCode: "090110",
  },
  {
    bankName: "VIRTUE MICROFINANCE BANK",
    CBNBankCode: "950",
    NIBBSCode: "090150",
  },
  {
    bankName: "VISA MICROFINANCE BANK",
    CBNBankCode: "944",
    NIBBSCode: "090139",
  },
  { bankName: "VTNETWORKS", CBNBankCode: "320", NIBBSCode: "100012" },
  { bankName: "WEMA BANK", CBNBankCode: "035", NIBBSCode: "000017" },
  {
    bankName: "WETLAND MICROFINANCE BANK",
    CBNBankCode: "916",
    NIBBSCode: "090120",
  },
  {
    bankName: "XSLNCE MICROFINANCE BANK",
    CBNBankCode: "928",
    NIBBSCode: "090124",
  },
  {
    bankName: "YES MICROFINANCE BANK",
    CBNBankCode: "946",
    NIBBSCode: "090142",
  },
  { bankName: "ZENITH BANK", CBNBankCode: "057", NIBBSCode: "000015" },
  { bankName: "ZENITH MOBILE", CBNBankCode: "322", NIBBSCode: "100018" },
  { bankName: "HERITAGE BANK", CBNBankCode: "030", NIBBSCode: "000020" },
  {
    bankName: "SUPPORT MICROFINANCE BANK",
    CBNBankCode: "295",
    NIBBSCode: "090446",
  },
];
